#!/bin/bash

for i in `ls $1`
do
filename="$1/$i"
echo "$filename"
cat $filename|awk -F',' '{print "[\""$1"\",\""$13"\"],"}'>$i.array

echo "  <html>
  <head>
    <script type=\"text/javascript\" src=\"https://www.gstatic.com/charts/loader.js\"></script>
    <script type=\"text/javascript\">
      var array1 = [];
      var chart;
      window.onkeyup = keyup;
      var bucketSize = 10;
      var fileUpload;

      //Listen to bucketSize dynamically
      function keyup(e) {
          bucketSize = e.target.value;
          google.charts.load(\"current\", {packages:[\"corechart\"]});
          google.charts.setOnLoadCallback(drawChart);
      }

      // console.log(\"bucketSize\", document.getElementById(\"bucketSize\"));
      var tableDataArray = [];
      var bucketRangeValues = [];
      function Upload() {
        array1 = [" > $i.html

sed '1d' $i.array >> $i.html

echo "];
              google.charts.load(\"current\", {packages:[\"corechart\"]});
              google.charts.setOnLoadCallback(drawChart);
      }

        function drawChart() {
         var data = google.visualization.arrayToDataTable(array1);
         var options = {
          title: 'intel data',
          legend: { position: 'none' },
          histogram: {bucketSize: bucketSize},
          enableInteractivity: true
        };

        chart = new google.visualization.Histogram(document.getElementById('chart_div'));
        chart.draw(data, options);
        google.visualization.events.addListener(chart, 'select', selectHandler);

        var min=0;
        var max=0;
        var minBucket;
        var maxBucket;
          //Find the min and max value
          for (var i = 0; i < array1.length; i++) {
            var value = parseFloat(array1[i][1]);
            if ( value < min )
              min = value;
            else if (value > max)
              max = value;
          }

          // console.log(\"min\",min,\"max\",max);
          //Find the min and max bucket emperical values
          if(bucketSize !== 0) {
            minBucket = parseInt(min/bucketSize);
            console.log(\"minBucketBefore\",minBucket);
            minBucket = minBucket <= 0 ? minBucket-1 : minBucket;
            maxBucket = parseInt(Math.ceil(max/bucketSize));
          }

          // console.log(\"minBucket\",minBucket,\"maxBucket\",maxBucket);
          //Actual bucket values
          var bucketRanges = [];
          for ( var i = minBucket; i < maxBucket; i++) {
            bucketRanges.push({bucketMin: i*bucketSize, bucketMax: (i+1)*bucketSize})
          }
          // console.log(\"bucketRanges\",bucketRanges);

          //Initialize bucketRanges
          for ( var i = 0; i < bucketRanges.length; i++){
            bucketRangeValues.push([[]]);
          }

          //Grouping by bucket ranges
          for (var i = 0; i < array1.length; i++) {
            var value = parseFloat(array1[i][1]);
            for (var j = 0; j < bucketRanges.length; j++) {
              if (value >= bucketRanges[j].bucketMin && value < bucketRanges[j].bucketMax)
                bucketRangeValues[j][0].push(array1[i]);
            }
          }
          // console.log(\"bucketRangeValues\", bucketRangeValues);
        }

        function selectHandler() {
          //Selection coordinates
          var selection = chart.getSelection();

          tableDataArray = bucketRangeValues[selection[0].row];
          console.log(tableDataArray);

          google.charts.load('current', {'packages':['table']});
          google.charts.setOnLoadCallback(drawTable);
        }

        function drawTable() {
          var data = new google.visualization.DataTable();
          data.addColumn('string', 'cell');
          data.addColumn('string', 'delta');
          data.addRows(tableDataArray[0]);

          var table = new google.visualization.Table(document.getElementById('table_div'));

          table.draw(data, {showRowNumber: true, width: '100%', height: '100%'});
        }

      </script>
    </head>
    <body onload=\"Upload()\">
      <label>Bucket Size</label>
      <input type=\"number\" id=\"bucketSize\" value=\"10\">
      <div id=\"chart_div\" style=\"width: 900px; height: 500px;\"></div>
      <div id=\"table_div\" style=\"width: 900px; height: 500px;\"></div>
    </body>
    </html>
" >> $i.html
rm $i.array
done
